/*
 * Dingo Mail AU API
 *
 * <p>API for api.dingomail.com.au</p> 
 *
 * The version of the OpenAPI document: 0.2.4
 * Contact: info@dingomail.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Au.Com.Dingomail.Api.Dingomailau.Client;
using Au.Com.Dingomail.Api.Dingomailau.Model;

namespace Au.Com.Dingomail.Api.Dingomailau.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOptoutsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get list of email addresses that have unsubscribed
        /// </remarks>
        /// <exception cref="Au.Com.Dingomail.Api.Dingomailau.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyid">The ID of the API Key being used</param>
        /// <returns>List&lt;GetUnsubscribes&gt;</returns>
        List<GetUnsubscribes> GetUnsubscribes(string keyid);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get list of email addresses that have unsubscribed
        /// </remarks>
        /// <exception cref="Au.Com.Dingomail.Api.Dingomailau.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyid">The ID of the API Key being used</param>
        /// <returns>ApiResponse of List&lt;GetUnsubscribes&gt;</returns>
        ApiResponse<List<GetUnsubscribes>> GetUnsubscribesWithHttpInfo(string keyid);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOptoutsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get list of email addresses that have unsubscribed
        /// </remarks>
        /// <exception cref="Au.Com.Dingomail.Api.Dingomailau.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyid">The ID of the API Key being used</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;GetUnsubscribes&gt;</returns>
        System.Threading.Tasks.Task<List<GetUnsubscribes>> GetUnsubscribesAsync(string keyid, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get list of email addresses that have unsubscribed
        /// </remarks>
        /// <exception cref="Au.Com.Dingomail.Api.Dingomailau.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyid">The ID of the API Key being used</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;GetUnsubscribes&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<GetUnsubscribes>>> GetUnsubscribesWithHttpInfoAsync(string keyid, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOptoutsApi : IOptoutsApiSync, IOptoutsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class OptoutsApi : IOptoutsApi
    {
        private Au.Com.Dingomail.Api.Dingomailau.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="OptoutsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public OptoutsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OptoutsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public OptoutsApi(string basePath)
        {
            this.Configuration = Au.Com.Dingomail.Api.Dingomailau.Client.Configuration.MergeConfigurations(
                Au.Com.Dingomail.Api.Dingomailau.Client.GlobalConfiguration.Instance,
                new Au.Com.Dingomail.Api.Dingomailau.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Au.Com.Dingomail.Api.Dingomailau.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Au.Com.Dingomail.Api.Dingomailau.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Au.Com.Dingomail.Api.Dingomailau.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OptoutsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public OptoutsApi(Au.Com.Dingomail.Api.Dingomailau.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Au.Com.Dingomail.Api.Dingomailau.Client.Configuration.MergeConfigurations(
                Au.Com.Dingomail.Api.Dingomailau.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Au.Com.Dingomail.Api.Dingomailau.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Au.Com.Dingomail.Api.Dingomailau.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Au.Com.Dingomail.Api.Dingomailau.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OptoutsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public OptoutsApi(Au.Com.Dingomail.Api.Dingomailau.Client.ISynchronousClient client, Au.Com.Dingomail.Api.Dingomailau.Client.IAsynchronousClient asyncClient, Au.Com.Dingomail.Api.Dingomailau.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Au.Com.Dingomail.Api.Dingomailau.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Au.Com.Dingomail.Api.Dingomailau.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Au.Com.Dingomail.Api.Dingomailau.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Au.Com.Dingomail.Api.Dingomailau.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Au.Com.Dingomail.Api.Dingomailau.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Get list of email addresses that have unsubscribed
        /// </summary>
        /// <exception cref="Au.Com.Dingomail.Api.Dingomailau.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyid">The ID of the API Key being used</param>
        /// <returns>List&lt;GetUnsubscribes&gt;</returns>
        public List<GetUnsubscribes> GetUnsubscribes(string keyid)
        {
            Au.Com.Dingomail.Api.Dingomailau.Client.ApiResponse<List<GetUnsubscribes>> localVarResponse = GetUnsubscribesWithHttpInfo(keyid);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get list of email addresses that have unsubscribed
        /// </summary>
        /// <exception cref="Au.Com.Dingomail.Api.Dingomailau.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyid">The ID of the API Key being used</param>
        /// <returns>ApiResponse of List&lt;GetUnsubscribes&gt;</returns>
        public Au.Com.Dingomail.Api.Dingomailau.Client.ApiResponse<List<GetUnsubscribes>> GetUnsubscribesWithHttpInfo(string keyid)
        {
            // verify the required parameter 'keyid' is set
            if (keyid == null)
            {
                throw new Au.Com.Dingomail.Api.Dingomailau.Client.ApiException(400, "Missing required parameter 'keyid' when calling OptoutsApi->GetUnsubscribes");
            }

            Au.Com.Dingomail.Api.Dingomailau.Client.RequestOptions localVarRequestOptions = new Au.Com.Dingomail.Api.Dingomailau.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Au.Com.Dingomail.Api.Dingomailau.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Au.Com.Dingomail.Api.Dingomailau.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("keyid", Au.Com.Dingomail.Api.Dingomailau.Client.ClientUtils.ParameterToString(keyid)); // header parameter

            // authentication (Key Secret) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("keysecret")))
            {
                localVarRequestOptions.HeaderParameters.Add("keysecret", this.Configuration.GetApiKeyWithPrefix("keysecret"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<GetUnsubscribes>>("/optouts", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUnsubscribes", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get list of email addresses that have unsubscribed
        /// </summary>
        /// <exception cref="Au.Com.Dingomail.Api.Dingomailau.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyid">The ID of the API Key being used</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;GetUnsubscribes&gt;</returns>
        public async System.Threading.Tasks.Task<List<GetUnsubscribes>> GetUnsubscribesAsync(string keyid, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Au.Com.Dingomail.Api.Dingomailau.Client.ApiResponse<List<GetUnsubscribes>> localVarResponse = await GetUnsubscribesWithHttpInfoAsync(keyid, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get list of email addresses that have unsubscribed
        /// </summary>
        /// <exception cref="Au.Com.Dingomail.Api.Dingomailau.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyid">The ID of the API Key being used</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;GetUnsubscribes&gt;)</returns>
        public async System.Threading.Tasks.Task<Au.Com.Dingomail.Api.Dingomailau.Client.ApiResponse<List<GetUnsubscribes>>> GetUnsubscribesWithHttpInfoAsync(string keyid, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'keyid' is set
            if (keyid == null)
            {
                throw new Au.Com.Dingomail.Api.Dingomailau.Client.ApiException(400, "Missing required parameter 'keyid' when calling OptoutsApi->GetUnsubscribes");
            }


            Au.Com.Dingomail.Api.Dingomailau.Client.RequestOptions localVarRequestOptions = new Au.Com.Dingomail.Api.Dingomailau.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Au.Com.Dingomail.Api.Dingomailau.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Au.Com.Dingomail.Api.Dingomailau.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("keyid", Au.Com.Dingomail.Api.Dingomailau.Client.ClientUtils.ParameterToString(keyid)); // header parameter

            // authentication (Key Secret) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("keysecret")))
            {
                localVarRequestOptions.HeaderParameters.Add("keysecret", this.Configuration.GetApiKeyWithPrefix("keysecret"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<GetUnsubscribes>>("/optouts", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUnsubscribes", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
