/*
 * Dingo Mail AU API
 *
 * <p>API for api.dingomail.com.au</p> 
 *
 * The version of the OpenAPI document: 0.2.4
 * Contact: info@dingomail.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Au.Com.Dingomail.Api.Dingomailau.Api;
using Au.Com.Dingomail.Api.Dingomailau.Model;
using Au.Com.Dingomail.Api.Dingomailau.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Au.Com.Dingomail.Api.Dingomailau.Test.Model
{
    /// <summary>
    ///  Class for testing CheckStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CheckStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CheckStatus
        //private CheckStatus instance;

        public CheckStatusTests()
        {
            // TODO uncomment below to create an instance of CheckStatus
            //instance = new CheckStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CheckStatus
        /// </summary>
        [Fact]
        public void CheckStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" CheckStatus
            //Assert.IsType<CheckStatus>(instance);
        }


        /// <summary>
        /// Test the property 'EmailID'
        /// </summary>
        [Fact]
        public void EmailIDTest()
        {
            // TODO unit test for the property 'EmailID'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

    }

}
