/*
 * Dingo Mail AU API
 *
 * <p>API for api.dingomail.com.au</p> 
 *
 * The version of the OpenAPI document: 0.2.4
 * Contact: info@dingomail.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Au.Com.Dingomail.Api.Dingomailau.Api;
using Au.Com.Dingomail.Api.Dingomailau.Model;
using Au.Com.Dingomail.Api.Dingomailau.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Au.Com.Dingomail.Api.Dingomailau.Test.Model
{
    /// <summary>
    ///  Class for testing EmailResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmailResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmailResponse
        //private EmailResponse instance;

        public EmailResponseTests()
        {
            // TODO uncomment below to create an instance of EmailResponse
            //instance = new EmailResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailResponse
        /// </summary>
        [Fact]
        public void EmailResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmailResponse
            //Assert.IsType<EmailResponse>(instance);
        }


        /// <summary>
        /// Test the property 'EmailID'
        /// </summary>
        [Fact]
        public void EmailIDTest()
        {
            // TODO unit test for the property 'EmailID'
        }
        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }

    }

}
