/*
 * Dingo Mail AU API
 *
 * <p>API for api.dingomail.com.au</p> 
 *
 * The version of the OpenAPI document: 0.2.4
 * Contact: info@dingomail.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Au.Com.Dingomail.Api.Dingomailau.Api;
using Au.Com.Dingomail.Api.Dingomailau.Model;
using Au.Com.Dingomail.Api.Dingomailau.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Au.Com.Dingomail.Api.Dingomailau.Test.Model
{
    /// <summary>
    ///  Class for testing GetUnsubscribes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetUnsubscribesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetUnsubscribes
        //private GetUnsubscribes instance;

        public GetUnsubscribesTests()
        {
            // TODO uncomment below to create an instance of GetUnsubscribes
            //instance = new GetUnsubscribes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetUnsubscribes
        /// </summary>
        [Fact]
        public void GetUnsubscribesInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetUnsubscribes
            //Assert.IsType<GetUnsubscribes>(instance);
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Fact]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }

    }

}
