/*
 * Dingo Mail AU API
 *
 * <p>API for api.dingomail.com.au</p> 
 *
 * The version of the OpenAPI document: 0.2.4
 * Contact: info@dingomail.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Au.Com.Dingomail.Api.Dingomailau.Api;
using Au.Com.Dingomail.Api.Dingomailau.Model;
using Au.Com.Dingomail.Api.Dingomailau.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Au.Com.Dingomail.Api.Dingomailau.Test.Model
{
    /// <summary>
    ///  Class for testing NewEmail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewEmailTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewEmail
        //private NewEmail instance;

        public NewEmailTests()
        {
            // TODO uncomment below to create an instance of NewEmail
            //instance = new NewEmail();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewEmail
        /// </summary>
        [Fact]
        public void NewEmailInstanceTest()
        {
            // TODO uncomment below to test "IsType" NewEmail
            //Assert.IsType<NewEmail>(instance);
        }


        /// <summary>
        /// Test the property 'Html'
        /// </summary>
        [Fact]
        public void HtmlTest()
        {
            // TODO unit test for the property 'Html'
        }
        /// <summary>
        /// Test the property 'Recipient'
        /// </summary>
        [Fact]
        public void RecipientTest()
        {
            // TODO unit test for the property 'Recipient'
        }
        /// <summary>
        /// Test the property 'SenderEmail'
        /// </summary>
        [Fact]
        public void SenderEmailTest()
        {
            // TODO unit test for the property 'SenderEmail'
        }
        /// <summary>
        /// Test the property 'SenderName'
        /// </summary>
        [Fact]
        public void SenderNameTest()
        {
            // TODO unit test for the property 'SenderName'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'UnsubLink'
        /// </summary>
        [Fact]
        public void UnsubLinkTest()
        {
            // TODO unit test for the property 'UnsubLink'
        }

    }

}
